version: '3'

services:
  recipe-page-server:
    image: "kw00hk/frd:latest"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
  postgres:
    image: "postgres:13"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recipe
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
